# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        edit_img:
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
                    allow_upscale: true

        list_img:
            filters:
                thumbnail:
                    size: [600,600]
                    mode: outbound
                    allow_upscale: true
                relative_resize: 
                    scale: 2  

        player_img:
            filters:
                thumbnail:
                    size: [400, 400]
                    mode: outbound
                    allow_upscale: true
                relative_resize: 
                    scale: 2    

        carousel:
            quality: 85
            filters:
                relative_resize: 
                    scale: 2
            


    
