# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"


    filter_sets:



        edit_img:
            filters:
                thumbnail:
                    size: [200,200]
                    mode: outbound
                    allow_upscale: true


        list_img:
            filters:
                upscale:
                    by: 2
                    mode: outbound

        player_img:
            filters:
                thumbnail:
                    size: [400,400]
                    mode: outbound
                    allow_upscale: true            