# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"


    filter_sets:
        carousel_img:
            filters:
                thumbnail:
                    size: [500,500]
                    mode: outbound
                    allow_upscale: true
        player_img:
            filters:
                thumbnail:
                    size: [400,400]
                    mode: outbound
                    allow_upscale: true